version: "3.9"
services:
  db:
    image: mariadb:10.6.4-focal
    container_name: MYSQL_db
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=drconsulta
      - MYSQL_USER=drconsulta
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    ports:
    - 3306:3306
  api:
    container_name: NEST_api
    build:
      dockerfile: Dockerfile
      context: ./desafio-entrevista-nodejs
      target: development
    volumes:
      - ./desafio-entrevista-nodejs:/usr/src/app
    env_file:
    - .env
    command: npm run start:dev
    ports:
      - 3001:3000
